name: flow
on: push
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: make setup
      - run: make test
      - run: make lint
      - name: Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
